import { useState } from 'react'
import { NavLink } from 'react-router-dom'
import { useSession } from '../Session'
import { api, apiFetch, API_BASE_URL } from '../api/transport'
import { CardVisual } from '../components/CardVisual'
import { toCardRecord, type ApiCard } from '../api/client'
import { Confirm, ErrorBox, Pager, RewardEditor, RewardList, SearchPick, cleanPositions, stamp, stateLabel, useAction, useRead, type Page, type Position } from '../components/Workflow'
import { SeasonAdmin } from './SeasonHub'

type Special = { id: number; card_id: number; name: string; state: string; edition: string; issued: number; supply_limit: number | null; card: ApiCard }
type Batch = { id: number; reason: string; items: Position[]; rows: { id: number; user_id: number; username: string; state: string; result: { error?: string; grant_id?: number } }[] }
type Preview = { preview_hash: string; rows: { user_id: number; username?: string; state: string; error?: string; preview?: { items: (Position & { before:number; after:number })[] } }[] }

export function AdvancedAdmin() {
  const { user } = useSession(); const [tab, setTab] = useState(user?.role === 'super_admin' ? 'special' : user?.role === 'admin' ? 'batch' : 'operations'); const [rev, setRev] = useState(0); const [page,setPage]=useState(1)
  const [operation, setOperation] = useState<{ path: string; body: Record<string,unknown>; title: string }>(); const act = useAction(); const [message,setMessage]=useState('')
  const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [edition,setEdition]=useState(''); const [rarity,setRarity]=useState('ultra_rare'); const [tradable,setTradable]=useState(true); const [limit,setLimit]=useState(''); const [image,setImage]=useState(''); const [fileError,setFileError]=useState('')
  const [users,setUsers]=useState<{id:number;name:string}[]>([]); const [items,setItems]=useState<Position[]>([]); const [reason,setReason]=useState(''); const [preview,setPreview]=useState<Preview>(); const [batchId,setBatchId]=useState<number>(); const [batchPassword,setBatchPassword]=useState(''); const [running,setRunning]=useState(false)
  const [correctionUser,setCorrectionUser]=useState<{id:number;username:string}>(); const [correctionKind,setCorrectionKind]=useState('points'); const [reference,setReference]=useState(0); const [quantity,setQuantity]=useState(1); const [confirmName,setConfirmName]=useState(''); const [correctionReason,setCorrectionReason]=useState(''); const [correctionPreview,setCorrectionPreview]=useState<{preview_hash:string;before:number;after:number}>()
  const specials=useRead<Page<Special>>(tab==='special'?`/admin/advanced/special-cards?page=${page}`:null,rev)
  const batches=useRead<Page<{id:number;reason:string;created_at:string}>>(tab==='batch'?`/admin/advanced/batches?page=${page}`:null,rev)
  const batch=useRead<Batch>(batchId?`/admin/advanced/batches/${batchId}`:null,rev)
  const ops=useRead<{inventory_consistent:boolean;journal_consistent:boolean;xp_consistent:boolean;pending_xp_events:number;reservations_consistent:boolean;reserved_cards:number;pending_batches:number;open_listings:number}>(tab==='operations'?'/admin/advanced/operations':null,rev)
  const reports=useRead<Page<{id:number;listing_id:number;user_id:number;reason:string;state:string}>>(tab==='moderation'?`/trade/moderation?page=${page}`:null,rev)
  const references=useRead<Page<{id:number;amount?:number;quantity?:number;reason?:string;name?:string;created_at?:string;kind?:string}>>(tab==='correction'&&correctionUser?`/admin/advanced/correction-sources/${correctionUser.id}?kind=${correctionKind}&page=${page}`:null,rev)
  const [days,setDays]=useState(0); const [exportSearch,setExportSearch]=useState('')
  const correctionBody={user_id:correctionUser?.id,confirmation:confirmName,kind:correctionKind,reference_id:reference,quantity,reason:correctionReason}
  async function execute(password:string,why:string) { if(!operation)return; const result=await act.run<{id?:number;audit_id?:number}>(operation.path,{...operation.body,password,reason:operation.body.reason || why}); if(result){setMessage(`Gespeichert · Vorgang #${result.id||result.audit_id||''}`);if(operation.path==='/admin/advanced/batches')setBatchId(result.id);setOperation(undefined);setRev(v=>v+1);setPreview(undefined);setCorrectionPreview(undefined)} }
  async function previewBatch(){const r=await act.run<Preview>('/admin/advanced/batches/preview',{user_ids:users.map(u=>u.id),items:cleanPositions(items),reason,password:'preview'});if(r)setPreview(r)}
  async function runBatch(){if(!batch.data||running)return;setRunning(true);try{await act.run(`/admin/advanced/batches/${batch.data.id}/run`,{password:batchPassword,reason:'Sammelvergabe nach geprüfter Empfängerliste ausführen'})}finally{setBatchPassword('');setRunning(false);setRev(v=>v+1)}}
  async function readFile(file?:File){setFileError('');if(!file)return;if(file.size>4*1024*1024){setFileError('Das Bild darf höchstens 4 MB groß sein.');return}const reader=new FileReader();reader.onload=()=>setImage(String(reader.result));reader.readAsDataURL(file)}
  async function exportUsers(){try{const res=await apiFetch(`${API_BASE_URL}/admin/advanced/users.csv?search=${encodeURIComponent(exportSearch)}`);if(!res.ok)throw new Error('Export fehlgeschlagen.');const url=URL.createObjectURL(await res.blob());const a=document.createElement('a');a.href=url;a.download='sdoycc-konten.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e){setMessage(e instanceof Error?e.message:'Export fehlgeschlagen.')}}
  if(!user||!['admin','super_admin','support_admin'].includes(user.role))return <div className="page-wrap"><h1>Kein Verwaltungszugriff</h1></div>
  const owner=user.role==='super_admin'
  return <div className="page-wrap workflow-page"><NavLink to="/admin">← Kontoverwaltung</NavLink><section className="workflow-hero"><p className="eyebrow">COMMUNITY-VERWALTUNG</p><h1>Aktionen & Inhalte</h1><p>Sonderkarten, gemeinsame Belohnungen und Saisons verwalten. Änderungen werden mit Begründung und Beleg gespeichert.</p></section><div className="workflow-nav">{[['special','Sonderkarten'],['batch','Sammelvergaben'],['correction','Korrekturen'],['moderation','Handelsmeldungen'],['season','Saisons'],['operations','Betrieb & Export']].filter(([v])=>owner||!['special','correction','season'].includes(v)).map(([v,t])=><button key={v} className={tab===v?'primary-button':'outline-button'} onClick={()=>{setTab(v);setPage(1)}}>{t}</button>)}</div>{message&&<p className="workflow-receipt" role="status">{message}</p>}<ErrorBox message={act.error||specials.error||batches.error||batch.error||ops.error||reports.error||references.error}/>
  {tab==='special'&&owner&&<><section className="content-panel"><h2>Community-Sonderkarte als Entwurf anlegen</h2><p>Eigene Karten bleiben vom offiziellen Katalog getrennt. Veröffentlichte Identitäten sind unveränderlich; neue Motive erhalten eine neue Karte.</p><div className="workflow-fields"><label>Name<input value={name} onChange={e=>setName(e.target.value)} maxLength={160}/></label><label>Edition<input value={edition} onChange={e=>setEdition(e.target.value)} maxLength={120}/></label><label>Seltenheit<select value={rarity} onChange={e=>setRarity(e.target.value)}>{[['common','Häufig'],['rare','Selten'],['super_rare','Superselten'],['ultra_rare','Ultraselten'],['secret_rare','Geheim selten']].map(([v,t])=><option value={v} key={v}>{t}</option>)}</select></label><label>Maximale Auflage (leer = unbegrenzt)<input type="number" min="1" max="1000000" value={limit} onChange={e=>setLimit(e.target.value)}/></label></div><label>Kartentext<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={3000}/></label><label className="workflow-check"><input type="checkbox" checked={tradable} onChange={e=>setTradable(e.target.checked)}/>Handelbare Karte</label><label>Kartenbild · PNG, JPEG oder WebP bis 4 MB<input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>void readFile(e.target.files?.[0])}/></label><ErrorBox message={fileError}/>{image&&<img src={image} alt="Vorschau der neuen Sonderkarte" style={{maxWidth:180,maxHeight:260,objectFit:'contain'}}/>}<button className="primary-button" disabled={name.length<3||!description||!edition||!image} onClick={()=>setOperation({path:'/admin/advanced/special-cards',title:'Sonderkarten-Entwurf speichern',body:{name,description,edition,rarity,tradable,supply_limit:limit?Number(limit):null,image}})}>Entwurf prüfen</button></section><section className="content-panel"><h2>Deine Sonderkarten</h2><div className="market-grid">{specials.data?.items.map(s=><article className="market-card" key={s.id}><div style={{maxWidth:150}}><CardVisual card={toCardRecord(s.card)} compact/></div><h3>{s.name}</h3><p>{stateLabel[s.state]} · {s.issued} / {s.supply_limit??'∞'} vergeben</p><button className="outline-button" onClick={()=>setOperation({path:`/admin/advanced/special-cards/${s.id}/state`,title:s.state==='active'?'Karte für weitere Vergaben archivieren':'Sonderkarte veröffentlichen',body:{state:s.state==='active'?'archived':'active'}})}>{s.state==='active'?'Archivieren':'Veröffentlichen'}</button></article>)}</div>{specials.data&&<Pager page={page} setPage={setPage} total={specials.data.total}/>}<p>Veröffentlichte Sonderkarten vergibst du im Bereich Sammelvergaben – auch an einen einzelnen Empfänger.</p></section></>}
  {tab==='batch'&&<><section className="content-panel"><h2>Belohnung für mehrere Konten</h2><SearchPick path="/admin/users?state=all&role=all" title="Empfänger auswählen" choose={u=>{setUsers(v=>v.some(x=>x.id===u.id)?v:[...v,{id:u.id,name:u.username||u.name}]);setPreview(undefined)}}/><div className="workflow-actions">{users.map(u=><button className="outline-button" key={u.id} onClick={()=>{setUsers(users.filter(x=>x.id!==u.id));setPreview(undefined)}}>{u.name} ×</button>)}</div><RewardEditor items={items} setItems={v=>{setItems(v);setPreview(undefined)}}/><label>Grund der Belohnung (sichtbar für Empfänger)<textarea value={reason} onChange={e=>{setReason(e.target.value);setPreview(undefined)}} minLength={5} maxLength={500}/></label><button className="primary-button" disabled={!users.length||!items.length||reason.length<5||act.busy} onClick={()=>void previewBatch()}>Alle Empfänger prüfen</button>{preview&&<div className="workflow-receipt"><h3>Vorschau · {preview.rows.length} Empfänger</h3>{preview.rows.map(r=><div key={r.user_id}><strong>{r.username||`Konto ${r.user_id}`} · {stateLabel[r.state]}</strong>{r.error&&<p>{r.error}</p>}{r.preview?.items.map((i,n)=><p key={n}>{i.name}: {i.before} → {i.after}</p>)}</div>)}<button className="primary-button" disabled={preview.rows.some(r=>r.state!=='ready')} onClick={()=>setOperation({path:'/admin/advanced/batches',title:'Empfängerliste und Belohnungen verbindlich speichern',body:{user_ids:users.map(u=>u.id),items:cleanPositions(items),reason,preview_hash:preview.preview_hash}})}>Sammelvergabe anlegen</button></div>}</section><section className="content-panel"><h2>Gespeicherte Sammelvergaben</h2>{batches.data?.items.map(b=><button key={b.id} className="outline-button" onClick={()=>setBatchId(b.id)}>#{b.id} · {b.reason}</button>)}{batches.data&&<Pager page={page} setPage={setPage} total={batches.data.total}/>}</section>{batch.data&&<section className="content-panel"><h2>Sammelvergabe #{batch.data.id}</h2><p>{batch.data.reason}</p><RewardList items={batch.data.items}/>{batch.data.rows.map(r=><p key={r.id}>{r.username}: <strong>{stateLabel[r.state]}</strong>{r.result.grant_id?` · Vergabe #${r.result.grant_id}`:''}{r.result.error&&` · ${r.result.error}`}</p>)}<p>Jede Empfängerzeile wird vollständig gebucht. Bei Abbruch kannst du fortsetzen; bereits ausgeführte Zeilen werden übersprungen.</p><label>Dein Administrator-Passwort<input type="password" autoComplete="current-password" value={batchPassword} onChange={e=>setBatchPassword(e.target.value)}/></label><button className="primary-button" disabled={!batchPassword||running||batch.data.rows.every(r=>r.state==='done')} onClick={()=>void runBatch()}>{running?'Vergabe läuft …':'Offene / abgelehnte Zeilen ausführen'}</button></section>}</>}
  {tab==='correction'&&owner&&<section className="content-panel"><h2>Originalbuchung nachvollziehbar korrigieren</h2><p>Hier werden ausschließlich noch verfügbare Mengen einer positiven Originalbuchung zurückgenommen. Reservierte Karten bleiben geschützt; historische Belege werden nicht verändert.</p><SearchPick path="/admin/users?state=all&role=all" title="Zielkonto" choose={u=>{setCorrectionUser({id:u.id,username:u.username||u.name});setReference(0);setCorrectionPreview(undefined)}}/>{correctionUser&&<p>Gewählt: @{correctionUser.username}</p>}<label>Bestandsart<select value={correctionKind} onChange={e=>{setCorrectionKind(e.target.value);setReference(0);setCorrectionPreview(undefined)}}><option value="points">Punkte</option><option value="card">Karten</option><option value="pack">Vergebene Packs</option></select></label><label>Positive Originalbuchung<select value={reference||''} onChange={e=>{setReference(Number(e.target.value));setCorrectionPreview(undefined)}}><option value="">Bitte wählen</option>{references.data?.items.map(r=><option value={r.id} key={r.id}>#{r.id} · +{r.amount||r.quantity} · {r.name||r.reason} {r.created_at?stamp(r.created_at):''}</option>)}</select></label>{references.data&&<Pager page={page} setPage={setPage} total={references.data.total}/>}<label>Zurückzunehmende Menge<input type="number" min="1" value={quantity} onChange={e=>{setQuantity(Number(e.target.value));setCorrectionPreview(undefined)}}/></label><label>Zielbenutzernamen exakt bestätigen<input value={confirmName} onChange={e=>{setConfirmName(e.target.value);setCorrectionPreview(undefined)}}/></label><label>Grund<textarea value={correctionReason} onChange={e=>{setCorrectionReason(e.target.value);setCorrectionPreview(undefined)}}/></label><button className="outline-button" disabled={!reference||correctionReason.length<5||!correctionUser} onClick={async()=>{const r=await act.run<typeof correctionPreview>('/admin/advanced/corrections/preview',{...correctionBody,password:'preview'});if(r)setCorrectionPreview(r)}}>Korrektur vorschauen</button>{correctionPreview&&<div className="workflow-receipt"><h3>Bestand: {correctionPreview.before} → {correctionPreview.after}</h3><button className="primary-button" onClick={()=>setOperation({path:'/admin/advanced/corrections',title:'Korrektur verbindlich buchen',body:{...correctionBody,preview_hash:correctionPreview.preview_hash}})}>Korrektur bestätigen</button></div>}</section>}
  {tab==='moderation'&&<section className="content-panel"><h2>Handelsmeldungen</h2><label>Optionale Handelssperre in Tagen (0 = keine)<input type="number" min="0" max="365" value={days} onChange={e=>setDays(Number(e.target.value))}/></label>{reports.data?.items.map(r=><article className="market-card" key={r.id}><NavLink to={`/trade/${r.listing_id}`}>Anzeige #{r.listing_id}</NavLink><p>{r.reason}</p><p>{stateLabel[r.state]}</p>{r.state==='open'&&user.role!=='support_admin'&&<div className="workflow-actions"><button className="outline-button" onClick={()=>setOperation({path:`/trade/moderation/${r.id}`,title:'Meldung ohne Schließung abschließen',body:{close_listing:false,restrict_days:0}})}>Keine Maßnahme</button><button className="primary-button" onClick={()=>setOperation({path:`/trade/moderation/${r.id}`,title:'Anzeige schließen und Reservierungen aufheben',body:{close_listing:true,restrict_days:days}})}>Moderieren</button></div>}</article>)}{reports.data&&<Pager page={page} setPage={setPage} total={reports.data.total}/>}</section>}
  {tab==='season'&&owner&&<SeasonAdmin/>}
  {tab==='operations'&&<section className="content-panel"><h2>Betriebsprüfung</h2>{ops.data?<><p>Karten- und Variantenbestand: <strong>{ops.data.inventory_consistent?'Stimmig':'Abweichung – prüfen'}</strong></p><p>Reservierungen: <strong>{ops.data.reservations_consistent?'Stimmig':'Abweichung – prüfen'}</strong> · {ops.data.reserved_cards} Karten</p><p>Kartenjournal: <strong>{ops.data.journal_consistent?"Stimmig":"Abweichung – prüfen"}</strong> · Saison-XP: <strong>{ops.data.xp_consistent?"Stimmig":"Abweichung – prüfen"}</strong></p><p>{ops.data.pending_xp_events} nachzuverarbeitende Saisonereignisse</p><p>{ops.data.open_listings} offene Anzeigen · {ops.data.pending_batches} nicht abgeschlossene Empfängerzeilen</p></>:<p>Lädt …</p>}<button className="outline-button" onClick={()=>setRev(v=>v+1)}>Prüfung aktualisieren</button>{owner&&<><label>Export nach Twitch-Namen filtern<input value={exportSearch} maxLength={100} onChange={e=>setExportSearch(e.target.value)}/></label><button className="outline-button" onClick={()=>void exportUsers()}>Konten als CSV exportieren</button></>}</section>}
  {operation&&<Confirm title={operation.title} admin busy={act.busy} error={act.error} close={()=>setOperation(undefined)} confirm={(p,r)=>void execute(p,r)}><p>Die Änderung wird dauerhaft protokolliert. Bei Vergaben bleibt die gespeicherte Empfängerliste maßgeblich.</p>{items.length>0&&tab==='batch'&&<RewardList items={items}/>}</Confirm>}
  </div>
}
