import { useState } from 'react'
import { NavLink, useNavigate, useSearchParams } from 'react-router-dom'
import { label } from '../i18n'
import { useSession } from '../Session'
import { CardVisual } from '../components/CardVisual'
import { toCardRecord } from '../api/client'
import { api } from '../api/transport'
import { Confirm, ErrorBox, PacketView, Pager, SearchPick, stamp, stateLabel, useAction, useRead, type Packet, type Page } from '../components/Workflow'

type Item = { variant_id: number; quantity: number }
type Wanted = { card_id: number; quantity: number; name?: string }
type Listing = { id: number; owner_id: number; owner: string; title: string; description: string; items: Packet[]; wanted: Wanted[]; state: string; version: number; expires_at: string; proposals?: Proposal[]; versions?: {version:number;created_at:string;snapshot:{description:string;wanted:Wanted[]}}[]; complete_set?: {name:string;definition:string} }
type Proposal = { id: number; user_id: number; user: string; listing_id: number; state: string; version: number; items: Packet[]; expires_at: string }
type Stock = Packet & { available: number; reserved: number }
type Receipt = { id: number; owner: string; partner: string; given: Packet[]; received: Packet[]; created_at: string }

function WantedEditor({ items, setItems }: { items: Wanted[]; setItems: (items: Wanted[]) => void }) {
  return <div><SearchPick path="/cards" title="Gesuchte Karte hinzufügen (jede nachgewiesene Ausgabe erlaubt)" choose={c => { if (!items.some(i => i.card_id === c.id)) setItems([...items, { card_id: c.id, quantity: 1, name: c.name }]) }} />{items.map((i,n) => <div className="workflow-actions" key={i.card_id}><strong>{i.name}</strong><label>Menge<input type="number" min="1" max="100" value={i.quantity} onChange={e => setItems(items.map((x,k) => k === n ? { ...x, quantity: Number(e.target.value) } : x))} /></label><button className="text-button" type="button" onClick={() => setItems(items.filter((_,k) => n !== k))}>Entfernen</button></div>)}</div>
}
function StockPicker({ items, setItems, completeSet }: { items: Packet[]; setItems: (items: Packet[]) => void; completeSet?: (id:number) => void }) {
  const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [setError, setSetError] = useState('')
  const stock = useRead<Page<Stock>>(`/trade/stock?search=${encodeURIComponent(search)}&page=${page}&page_size=12`)
  async function chooseSet(id: number) { try { const result = await api<{ items: Packet[]; complete: boolean; missing: string[]; definition: string }>(`/trade/sets/${id}/preview`); if (!result.complete) { setSetError(`Set unvollständig: ${result.missing.join(', ')}`); return } setItems(result.items); completeSet?.(id); setSetError(result.definition) } catch(e) { setSetError(e instanceof Error ? e.message : 'Set konnte nicht geladen werden.') } }
  return <section><h3>Deine verfügbaren Varianten</h3><p>Ungeklärter Altbestand und kontogebundene Karten werden nicht angeboten. Reservierte Karten bleiben in deiner Sammlung sichtbar.</p><details><summary>Vollständiges Kartenset zusammenstellen</summary><SearchPick path="/sets" title="Set suchen" choose={s => void chooseSet(s.id)} />{setError && <p role="status">{setError}</p>}</details><label>Im Bestand suchen<input value={search} onChange={e => { setSearch(e.target.value); setPage(1) }} /></label><ErrorBox message={stock.error} />{stock.data?.items.map(s => <div className="stock-option" key={s.variant_id}><CardVisual card={toCardRecord(s.card)} compact /><div><strong>{s.card.name}</strong><p>{s.available} verfügbar · {s.reserved} reserviert</p><label>Menge im Paket<input type="number" min="0" max={s.available} value={items.find(i => i.variant_id === s.variant_id)?.quantity || 0} onChange={e => { const q = Number(e.target.value); setItems([...items.filter(i => i.variant_id !== s.variant_id), ...(q>0 ? [{ ...s, quantity:q }] : [])]) }} /></label></div></div>)}{stock.data && <Pager page={page} setPage={setPage} total={stock.data.total} size={12} />}<h4>Dein Paket · {items.reduce((a,i)=>a+i.quantity,0)} Karten</h4><PacketView items={items} /></section>
}

export function TradeHub({ listingId }: { listingId?: number }) {
  const { user } = useSession(); const navigate = useNavigate(); const [params] = useSearchParams(); const tab = params.get('tab') || 'discover'; const [rev, setRev] = useState(0)
  const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [fulfillable, setFulfillable] = useState(false); const [filter, setFilter] = useState(''); const [side, setSide] = useState('offered')
  const [selectedSet, setSelectedSet] = useState<{ id: number; name: string }>(); const [selectedCard, setSelectedCard] = useState<{ id: number; name: string }>(); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [days, setDays] = useState(7)
  const [completeSetId,setCompleteSetId] = useState<number>(); const [items, setItems] = useState<Packet[]>([]); const [wanted, setWanted] = useState<Wanted[]>([]); const [operation, setOperation] = useState<{ path: string; body: unknown; title: string; give?: Packet[]; receive?: Packet[] }>(); const [message, setMessage] = useState(''); const [reportReason, setReportReason] = useState('')
  const config=useRead<{proposal_hours:number;max_listings:number;max_proposals:number}>('/trade/config');
  const act = useAction(); const list = useRead<Page<Listing>>(!listingId && ['discover','mine'].includes(tab) ? `/trade/listings?mine=${tab==='mine'}&search=${encodeURIComponent(search)}&page=${page}&fulfillable=${fulfillable}&rarity=${filter}&side=${side}${selectedCard ? `&card_id=${selectedCard.id}`:''}${selectedSet ? `&set_id=${selectedSet.id}`:''}` : null, rev)
  const detail = useRead<Listing>(listingId ? `/trade/listings/${listingId}` : null, rev)
  const proposals = useRead<Page<Proposal>>(!listingId && tab==='offers' ? `/trade/me/proposals?page=${page}` : null,rev)
  const history = useRead<Page<Receipt>>(!listingId && tab==='history' ? `/trade/me/history?page=${page}` : null,rev)
  function switchTab(t: string) { navigate(`/trade?tab=${t}`); setPage(1); setMessage('') }
  async function execute() { if (!operation) return; const result = await act.run<{ id: number }>(operation.path,operation.body); if (result) { setOperation(undefined); setRev(x=>x+1); setMessage(`Vorgang gespeichert · #${result.id || ''}`); if (operation.path === '/trade/listings') navigate(`/trade/${result.id}`) } }
  const itemBody = items.map(({ variant_id, quantity })=>({variant_id,quantity})); const wantedBody = wanted.map(({card_id,quantity})=>({card_id,quantity}))
  const d = detail.data
  return <div className="page-wrap workflow-page"><section className="workflow-hero"><p className="eyebrow">KARTEN VERBINDEN</p><h1>Der Tauschplatz</h1><p>Stelle ein Kartenpaket zusammen, finde die passende Gegenleistung und tausche beide Pakete mit einem verbindlichen Abschluss.</p></section><nav className="workflow-nav" aria-label="Handelsbereiche">{[['discover','Anzeigen entdecken'],['mine','Meine Anzeigen'],['offers','Meine Angebote'],['history','Tauschbelege'],['create','Anzeige erstellen']].map(([v,t])=><button className={tab===v&&!listingId?'primary-button':'outline-button'} key={v} onClick={()=>switchTab(v)}>{t}</button>)}</nav>{message&&<p className="workflow-receipt" role="status">{message}</p>}<ErrorBox message={act.error||list.error||detail.error||proposals.error||history.error}/>
    {!listingId && ['discover','mine'].includes(tab) && <><section className="content-panel"><div className="workflow-fields"><label>Anzeige suchen<input value={search} onChange={e=>{setSearch(e.target.value);setPage(1)}}/></label><label>Seltenheit<select value={filter} onChange={e=>{setFilter(e.target.value);setPage(1)}}><option value="">Alle</option>{['common','rare','super_rare','ultra_rare','secret_rare'].map(r=><option value={r} key={r}>{label(r)}</option>)}</select></label><label>Seite des Kartenfilters<select value={side} onChange={e=>setSide(e.target.value)}><option value="offered">Angebotene Karten</option><option value="wanted">Gesuchte Karten</option></select></label></div><label className="workflow-check"><input type="checkbox" checked={fulfillable} onChange={e=>{setFulfillable(e.target.checked);setPage(1)}}/>Nur erfüllbare Gesuche</label><details><summary>{selectedCard?`Kartenfilter: ${selectedCard.name}`:'Nach einer Karte filtern'}</summary><SearchPick path="/cards" title="Kartenfilter" choose={c=>{setSelectedCard(c);setPage(1)}}/><button className="text-button" onClick={()=>setSelectedCard(undefined)}>Kartenfilter entfernen</button></details><details><summary>{selectedSet?`Setfilter: ${selectedSet.name}`:"Nach einem Set filtern"}</summary><SearchPick path="/sets" title="Setfilter" choose={s=>{setSelectedSet(s);setPage(1)}}/><button className="text-button" onClick={()=>setSelectedSet(undefined)}>Setfilter entfernen</button></details></section>{!list.data?<p>Lädt …</p>:<><div className="market-grid">{list.data.items.map(row=><article className="market-card" key={row.id}><span className="market-badge">{stateLabel[row.state]}</span><h2><NavLink to={`/trade/${row.id}`}>{row.title}</NavLink></h2><p>Von {row.owner} · bis {stamp(row.expires_at)}</p><PacketView items={row.items.slice(0,3)}/><p>{row.items.length} Varianten im Paket</p><strong>Gesucht</strong><p>{row.wanted.map(i=>`${i.quantity} × ${i.name}`).join(', ')||'Offen für passende Angebote'}</p></article>)}</div>{!list.data.items.length&&<div className="workflow-empty">Noch keine passenden Anzeigen. Erstelle das erste Kartenpaket.</div>}<Pager page={page} setPage={setPage} total={list.data.total}/></>}</>}
    {!listingId&&tab==='create'&&<section className="content-panel"><h2>Neues Kartenpaket</h2><label>Titel<input maxLength={160} minLength={3} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Beschreibung<textarea maxLength={1000} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Laufzeit in Tagen<input type="number" min="1" max="30" value={days} onChange={e=>setDays(Number(e.target.value))}/></label><StockPicker items={items} setItems={v=>{setItems(v);setCompleteSetId(undefined)}} completeSet={setCompleteSetId}/><WantedEditor items={wanted} setItems={setWanted}/><p>Der Entwurf reserviert noch keine Karten. Erst die Veröffentlichung bindet dein Paket bis zum Ablauf oder zur Stornierung.</p><button className="primary-button" disabled={title.length<3||!items.length} onClick={()=>setOperation({path:'/trade/listings',body:{title,description,days,items:itemBody,wanted:wantedBody,complete_set_id:completeSetId},title:'Entwurf speichern',give:items})}>Entwurf prüfen</button></section>}
    {listingId&&!d&&!detail.error&&<p>Anzeige wird geladen …</p>}{d&&<><section className="content-panel"><span className="market-badge">{stateLabel[d.state]} · Version {d.version}</span><h2>{d.title}</h2><p>Von {d.owner} · bis {stamp(d.expires_at)}</p><p>{d.description}</p>{d.complete_set&&<p className="workflow-receipt">Vollständiges Set: {d.complete_set.name} · {d.complete_set.definition}</p>}<h3>Angebotenes Paket</h3><PacketView items={d.items}/><details><summary>Bisherige Tauschbedingungen</summary>{d.versions?.map(v=><article key={v.version}><strong>Version {v.version} · {stamp(v.created_at)}</strong><p>{v.snapshot.description}</p><p>{v.snapshot.wanted.map(w=>`${w.quantity} × ${w.name}`).join(", ")||"Offen für passende Angebote"}</p></article>)}</details><h3>Gesuchte Karten</h3><ul>{d.wanted.map(i=><li key={i.card_id}>{i.quantity} × {i.name} · jede nachgewiesene Ausgabe</li>)}</ul>{!d.wanted.length&&<p>Offen für passende Angebote.</p>}{d.owner_id===user?.id?<div className="workflow-actions">{d.state==='draft'&&<button className="primary-button" onClick={()=>setOperation({path:`/trade/listings/${d.id}/publish`,body:{version:d.version},title:'Paket verbindlich reservieren und veröffentlichen',give:d.items})}>Veröffentlichen</button>}{['draft','open'].includes(d.state)&&<button className="outline-button" onClick={()=>setOperation({path:`/trade/listings/${d.id}/cancel`,body:{version:d.version},title:'Anzeige stornieren und alle Reservierungen lösen'})}>Anzeige zurückziehen</button>}</div>:<details><summary>Anzeige melden oder Anbieter blockieren</summary><label>Grund<textarea value={reportReason} onChange={e=>setReportReason(e.target.value)} minLength={5} maxLength={500}/></label><button className="outline-button" disabled={reportReason.length<5} onClick={()=>setOperation({path:`/trade/reports/${d.id}`,body:{reason:reportReason},title:'Anzeige zur Prüfung melden'})}>Melden</button><button className="outline-button" onClick={()=>setOperation({path:`/trade/blocks/${d.owner_id}`,body:{blocked:true},title:'Anbieter blockieren und gemeinsame offene Angebote aufheben'})}>Handel blockieren</button><button className="text-button" onClick={()=>setOperation({path:`/trade/blocks/${d.owner_id}`,body:{blocked:false},title:'Eigene Blockierung dieses Anbieters aufheben'})}>Blockierung aufheben</button></details>}</section>
    {d.state==='open'&&d.owner_id!==user?.id&&<section className="content-panel"><h2>Deine Gegenleistung</h2><StockPicker items={items} setItems={setItems}/><p>Deine Karten werden bis zu {config.data?.proposal_hours || 48} Stunden reserviert. Der Anbieter kann das gesamte Paket verbindlich annehmen. Du kannst dein offenes Angebot jederzeit zurückziehen.</p><button className="primary-button" disabled={!items.length} onClick={()=>setOperation({path:`/trade/proposals/to/${d.id}`,body:{version:d.version,items:itemBody},title:'Verbindliches Tauschangebot senden',give:items,receive:d.items})}>Angebot prüfen</button></section>}
    {d.state==='open'&&d.owner_id===user?.id&&<details className="content-panel"><summary>Gesuch ändern / neue Gegenangebotsversion</summary><p>Alle bisherigen Angebote werden aufgehoben und müssen erneut bestätigt werden. Dein angebotenes Paket bleibt reserviert.</p><WantedEditor items={wanted} setItems={setWanted}/><label>Neue Beschreibung<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={1000}/></label><button className="outline-button" disabled={!wanted.length} onClick={()=>setOperation({path:`/trade/counter/${d.id}`,body:{version:d.version,wanted:wantedBody,description},title:'Neue Tauschbedingungen veröffentlichen'})}>Neue Version prüfen</button></details>}
    <section className="content-panel"><h2>{d.owner_id===user?.id?'Eingegangene Angebote':'Deine Angebote zu dieser Anzeige'}</h2>{!d.proposals?.length&&<p>Noch keine Angebote.</p>}{d.proposals?.map(p=><article className="market-card" key={p.id}><h3>{p.user} · {stateLabel[p.state]}</h3><p>Gültig bis {stamp(p.expires_at)}</p><PacketView items={p.items}/>{p.state==='pending'&&<div className="workflow-actions">{d.owner_id===user?.id?<><button className="primary-button" onClick={()=>setOperation({path:`/trade/proposals/${p.id}/accept`,body:{version:p.version},title:'Tausch verbindlich abschließen',give:d.items,receive:p.items})}>Annehmen</button><button className="outline-button" onClick={()=>setOperation({path:`/trade/proposals/${p.id}/reject`,body:{version:p.version},title:'Angebot ablehnen'})}>Ablehnen</button></>:<button className="outline-button" onClick={()=>setOperation({path:`/trade/proposals/${p.id}/withdraw`,body:{version:p.version},title:'Angebot zurückziehen'})}>Zurückziehen</button>}</div>}</article>)}</section></>}
    {!listingId&&tab==='offers'&&<section className="content-panel"><h2>Deine gesendeten Angebote</h2>{proposals.data?.items.map(p=><article key={p.id}><NavLink to={`/trade/${p.listing_id}`}>Anzeige #{p.listing_id} öffnen</NavLink><p>{stateLabel[p.state]}</p><PacketView items={p.items}/></article>)}{proposals.data&&!proposals.data.items.length&&<p>Noch keine Angebote gesendet.</p>}{proposals.data&&<Pager page={page} setPage={setPage} total={proposals.data.total}/>}</section>}
    {!listingId&&tab==='history'&&<section className="content-panel"><h2>Unveränderliche Tauschbelege</h2>{history.data?.items.map(r=><details key={r.id}><summary>Beleg #{r.id} · {r.owner} ↔ {r.partner} · {stamp(r.created_at)}</summary><h3>{r.owner} gab</h3><PacketView items={r.given}/><h3>{r.partner} gab</h3><PacketView items={r.received}/></details>)}{history.data&&!history.data.items.length&&<p>Noch keine abgeschlossenen Tausche.</p>}{history.data&&<Pager page={page} setPage={setPage} total={history.data.total}/>}</section>}
    {operation&&<Confirm title={operation.title} busy={act.busy} error={act.error} close={()=>setOperation(undefined)} confirm={()=>void execute()}>{operation.give&&<><h3>Du gibst / reservierst</h3><PacketView items={operation.give}/></>}{operation.receive&&<><h3>Du erhältst</h3><PacketView items={operation.receive}/><p>Der Abschluss überträgt beide Pakete gemeinsam. Ein abgeschlossener Tausch kann nicht regulär rückgängig gemacht werden.</p></>}</Confirm>}
  </div>
}
